version: '1.0'
services:
  web:
    build: ./ui
    ports:
     - "3000:3000"
  mobile:
    build: ./native-ui/
    ports:
      - "2000:2000"
  api:
    build: ./api/infra/k8s
    ports:
      - "4000:4000"