version: '3'
services:
  auth-srvc:
    image: ""
    container_name: 
    ports:
      - 5432:5432
  auth-srvc:
    image: ""
    container_name: 
    ports:
      - 5432:5432
  auth-srvc:
    image: ""
    container_name: 
    ports:
      - 5432:5432
  auth-srvc:
    image: ""
    container_name: 
    ports:
      - 5432:5432
  auth-srvc:
    image: ""
    container_name: 
    ports:
      - 5432:5432
  web:
    build: ./ui
    container_name: react-container
    ports:
      - 8080:8080
    links:
      - node-api
  mobile:
    build: ./native-ui
    container_name: mobile-container
    ports:
      - 4040:80
    links:
      - node-api